title: KG-BIAS 2020
description: Bias in Automatic Knowledge Graph Construction: A Workshop at AKBC 2020 (KG-BIAS 2020)
show_downloads: false
google_analytics: UA-157009293-1
theme: jekyll-theme-midnight
